Starting.Basal_Features <- c(
   "Ptn",        "Krt5",       "Dapl1",      "Fmo6",       "Tp63",       "Tmprss11a",  "Pkp1",      
  "Cxcl12",     "Wnt10a",     "Trim29",     "Dlk2",       "Serpinb5",   "Linc00176",  "Scgb1c1",   
  "Aqp3",       "Krt17",      "Col17a1",    "Mt2A",       "Bcl11a",     "Trpm3",      "Scn3b",     
  "Krt15",      "Serpinb10",  "Dcn",        "Meis1",      "Itga6",      "Klhl29",     "Bhlhe40",   
  "Nkain3",     "Ifitm3",     "Il33",       "Ltbp4",      "Meis2",      "Krt14",      "Abi3bp",    
   "Serpinb1a",  "Synpo2",     "Nectin1",    "Dnajb1",     "Comt",       "S100a13",    "AC128960.1",
   "Dst",        "F3",         "Dhrs3",      "St6galnac2", "Egfr",       "Igfbp2",     "Ucp2",      
   "Zfp36l1",    "S100a16",    "Egr1",       "Atf3",       "Rpl3",       "Rpl4",       "Ets1",      
   "Nfia",       "Rpl36a",     "Eef1b2",     "Tpt1",       "Gstm2",      "Rps9l1",     "Rpl7",      
   "Rps3",       "Spry1",      "Rps16",      "Rack1",      "Rps18",      "Junb",       "Rpl12",     
   "Rps28",      "RT1-A1",     "Rpl13",      "Rplp0",      "Rps3a",      "Rps21",      "Eef1g",     
  "Rbms3",      "Rps20",      "Rps5",       "Rpsa",       "Npm1",       "Rpl17",      "Eef2",      
   "Rps23",      "Rpl18a",     "Rpl23",      "Rpl14",      "Rpl28",      "Rps12",      "Rps4x",     
   "Rps2",       "Rps15",      "RT1-CE10",   "Rpl37",      "B2m",        "Jun",        "Rps27",     
   "Rpl19",      "Rpl15",      "Rpl41",      "Rps11",      "Rpl35",      "Slc25a4",    "Ier2",      
 "Rpl29",      "Prdx2",      "Rpl11",      "Naca",       "Mt-atp6",    "Mt-nd4",     "Itm2b",     
   "Mt-nd1",     "AY172581.24"
  
  
)

P0.Basal_Features <- c(
  "Wnt10a",    "Tp63",      "Col17a1",   "Itga2",     "Dapl1",     "Dlk2",      "Snai2",     "Cdh13",    
  "Tgfbi",     "Wnt6",      "Cyp26b1",   "Vsnl1",     "Plek2",     "Slc8a1",    "Fermt1",    "Krt5",     
   "Chst15",    "Adssl1",    "Kcnq5",     "Rgs10",     "Pdlim1",    "Gpnmb",     "Slc1a3",    "Sertad4",  
  "Col18a1",   "Itga6",     "Slc27a3",   "Ltbp4",     "Stom",      "Dst",       "Fam25a",    "Itgb4",    
   "Ptprs",     "Comt",      "Jag2",      "RGD1563365","Mcfd2",     "Pomgnt1",   "Atp1b3",    "Sema5a",   
  "Impdh2",    "Rpl32.1",   "Myc",       "Nrg1",      "RGD1562420","Iffo2",     "Anxa8",     "Npm1",     
  "Rps4x-ps9", "Rpl12",     "Rps25",     "Rps12",     "Rpl10a",    "Rpl4",      "Rpl30",     "Rps20",    
  "Rpl17",     "Rbbp8",     "Rps18",     "Rpl21.3",   "Rps10l1",   "Rps27a",    "Rps13",     "Rpl36a",   
  "Rps17",     "Rps19",     "Rps2",      "Rack1",     "Slc38a2",   "Rpl3",      "Rpl26",     "Rps11",    
 "Rps5",      "Rpl31",     "Rpl5",      "Rps8",      "Rps16",     "Rpsa",      "Rpl32",     "Rps3a",    
  "Rps15a",    "Rps3",      "Rpl28",     "Igfbp3",    "Rplp0",     "Antxr1",    "Rps4x",     "Eef1a1",   
  "Rpl15",     "Rpl13a",    "Rpl6",      "Rps9l1",    "Rpl27a",    "Rpl36",     "Rpl18a",    "Nfat5",    
 "Rpl22",     "Rpl10",     "Oscp1",     "AC141489.1","Rps24",     "Rpl29",     "Rpl27",     "Rpl24",    
  "Rpl23",     "Rps15",     "Nob1",      "Ptges3l",   "Rpl35",     "Rpl39",     "Eef2",      "Rnf43",    
 "Rpl11",     "Rps27"   
  
  
  
)

P3.Basal_Features <- c(
   "Wnt3a",     "Dsc3",      "Il17b",     "Bmx",       "Cxcl14",    "Mmp3",      "Ifitm10",   "Wnt10a",   
  "Sgca",      "Dll1",      "Hmga2",     "Tp63",      "Cdh13",     "Spon2",     "Galnt6",    "Serpinb10",
 "Krt42",     "Tnc",       "Col17a1",   "Plek2",     "Slc7a8",    "Has3",      "Crlf1",     "Bcl11b",   
  "Samd12",    "Fermt1",    "Gfod1",     "Tns4",      "Itga2",     "Tnik",      "Camk2b",    "Chst15",   
   "Adssl1",    "Kcnab1",    "Krt14",     "Itpk1",     "Rasl10a",   "Fscn1",     "Ptges",     "Procr",    
  "Slc2a9",    "Il6r",      "RGD1309104","Sh3pxd2a",  "Ramp1",     "Antxr1",    "Adarb1",    "Slc39a6",  
   "Snai2",     "Peg3",      "Krt5",      "Rgs12",     "Btbd11",    "Mctp2",     "Abca4",     "Bmp7",     
  "Ahcyl2",    "Adamts6",   "Eif4e3",    "Ano1",      "Fgf9",      "Anxa8",     "Vsnl1",     "Fgfr2",    
   "Itgb4",     "Pdlim1",    "B3gnt2",    "Slc35e4",   "Efnb1",     "Dst",       "Sema5a",    "Vwa1",     
  "Ppp2r3a",   "Plod1",     "Col18a1",   "Fam25a",    "Itga6",     "Nrg1",      "Tpmt",      "Tinagl1",  
   "Cotl1",     "Comt",      "Fcgr2a",    "Cdh3",      "Cd44",      "Ppp1r18",   "Mtss1",     "Ggh",      
  "Iffo2",     "Gss",       "Gja1",      "Eva1b",     "Ptpn1",     "Enah",      "Aig1",      "Asap2",    
  "Parvb",     "Sox9",      "Dnajc15",   "P4ha1",     "Mcfd2",     "Hspa8",     "Cdkl2",     "Impdh2",   
   "Npm1",      "Nradd",     "Dusp7",     "Cib2",      "Txndc17",   "Nucb1",     "Armcx3",    "Fdps",     
   "Padi4",     "Igfbp3",    "Serpinb6a", "Rab38",     "Nme2",      "Hsp90ab1",  "Polr3h",    "Porcn",    
   "Nob1",      "Lamb3",     "Igfbp7" 
  
  
)


Eng24Hr.Basal_Features <- c(
  "Dlk2",      "Cym",       "Crlf1",     "Cxcl14",    "Dll1",      "Ska1",      "Wnt10a",    "Inka1",    
 "Il17b",     "Rrm2",      "Rad51",     "Adssl1",    "Pbk",       "Pttg1",     "Knstrn",    "Clmp",     
 "Spc25",     "Tacc3",     "Plk1",      "Fscn1",     "Ooep",      "Wnt3a",     "Asf1b",     "Pclaf",    
  "Birc5",     "Nuf2",      "Hmmr",      "Racgap1",   "Duoxa1",    "Sox15",     "Uhrf1",     "Ube2t",    
 "Ercc6l",    "Lexm",      "Cdt1",      "Dscc1",     "Csrp2",     "Mybl2",     "Tk1",       "Slc16a3",  
 "Cdkn3",     "Aloxe3",    "Spon2",     "Shcbp1",    "Hist1h2bk", "Spc24",     "Depdc1",    "Exo1",     
  "Mmp3",      "Bub1",      "Ttk",       "Ptges",     "Tgfb1",     "Tpx2",      "Melk",      "Pole2",    
  "Snai2",     "Exoc3l2",   "Kcnn4",     "Ltb4r",     "Gins1",     "Mlf1",      "Sapcd2",    "Cdx2",     
  "Procr",     "Arhgap11a", "Tppp3",     "Cdk1",      "Prc1",      "Haus4",     "Aurka",     "Esco2",    
   "Ncapg",     "Bnc1",      "Egln3",     "Bub1b",     "Rad54l",    "Fermt1",    "Fbxo5",     "Cgas",     
  "F2rl2",     "Gnb4",      "Plek2",     "Spag5.1",   "Acer2",     "Ube2c",     "Plk4",      "Hmga1",    
  "Dtl",       "Ehd3",      "Gpsm2",     "Itpk1",     "Dlgap5",    "Mad2l1",    "Hist1h1b",  "Lipg",     
  "Mcm5",      "Ckap2",     "Chaf1b",    "Slc7a8",    "Cyp2s1",    "Aurkb",     "Rgs19",     "Has3",     
  "Ncaph",     "Wisp1",     "Cip2a",     "Ska3",      "Tp63",      "Trip13",    "Mki67",     "Rad51ap1", 
  "Tns4",      "Bcl11b",    "Mms22l",    "Smyd4",     "Galnt6",    "Mcm10",     "Ddias",     "E2f7",     
  "Bard1",     "Pfkp",      "Igfbp2",    "Sfrp1",     "Mnd1",      "Scd",       "Fen1",      "Adcy3",    
  "Col17a1",   "Hist1h2an", "Knl1",      "Bmp7",      "Cth",       "Ticrr",     "Stom",      "Dnmt3b",   
   "Chst15",    "Phospho1",  "Ptgs1",     "Mastl",     "Cln6",      "Axin2",     "Edaradd",   "Nusap1",   
  "Atad2",     "Timeless",  "Gins2",     "Rpa2",      "Lmo1",      "Slc7a11",   "Trim59",    "Sgo2",     
 "Ect2",      "Rgs12",     "Mcm3",      "Sema5a",    "Necab3",    "Emp3",      "Vwa1",      "Pole",     
  "Hirip3",    "Lmnb1",     "Mcm4",      "Dbf4",      "Dctpp1",    "Serpine1",  "Rgs3",      "Slc27a3",  
   "Pak6",      "Tnfrsf26",  "Fgfbp1",    "Krt5",      "Rfc4",      "Nrm",       "P2ry1",     "Hmgb2",    
   "Mcm6",      "Tube1",     "Depdc7",    "Ncapg2",    "Atad5",     "Nppb",      "Arhgap22",  "Fancd2",   
   "Zwilch",    "Dnph1",     "Brca1",     "Pdp2",      "Incenp",    "Slc35e4",   "Toe1",      "RGD1309104",
   "Brip1",     "Lig1",      "Serpinb10", "Chaf1a",    "Itga2",     "Zfp367",    "Sh3bp1",    "Mis18a",   
   "Car12",     "Usp1",      "Anxa8",     "Rrm1",      "Suv39h1l1", "Fam167a",   "Mcm7",      "Rfc5",     
   "Ripk3",     "Cks2",      "Rps6ka4",   "Haus7",     "Donson",    "Spr",       "Slc2a1",    "Jag2",     
   "Aspm",      "Tpmt",      "H2afz",     "Anln",      "Haus6",     "Prim2",     "Pold1",     "Gen1",     
   "Stard4",    "Peg3",      "Cdk2",      "Haus3",     "Ubash3b",   "Vrk2",      "Tinagl1",   "Fam136a",  
   "Slc7a5",    "Creg1",     "Exosc8",    "Dhfr",      "Slc25a15",  "Prim1",     "Rad18",     "Chsy1",    
   "Slc16a13",  "Polr3g",    "Elovl6",    "Pdlim1",    "Ptn",       "Nmral1",    "Pard6g",    "Mthfd2",   
   "Spdl1",     "Dut",       "Rfc2",      "Psat1",     "Cdh13",     "Nasp",      "Btbd11",    "Pdk1",     
   "Rpa1",      "Slc16a1",   "Rfc3",      "Nup43",     "Cdh3",      "Hmgn2",     "Samd12",    "Siva1",    
   "Hat1",      "Topbp1",    "Pola1",     "Mb21d2",    "Ifrd2",     "Nav3",      "Dnmt1",     "Prr5",     
   "Vrk1",      "Cotl1",     "Crtapl1",   "Tmem97",    "Ahcyl2",    "Lyar",      "Tuba1c",    "Shmt2",    
   "Slc39a6",   "Polr1e",    "Orc6",      "Mcm2",      "St6galnac4","Mthfd1",    "Scarb1",    "Gmnn",     
   "Dek",       "Gins4",     "Rp9",       "Foxn2",     "Taf4b",     "Eif4e3",    "Oaf",       "Slc1a5",   
   "Hmg1l1",    "Pcna",      "Igsf8",     "Fem1b",     "Lsm2",      "Dusp7",     "Fosl1",     "Pmf1",     
   "Smc4",      "Wdhd1",     "Trex1",     "Pcsk9",     "Fgfr2",     "RGD1597339","Acat2l1",   "Pold2",    
   "Dst",       "Gss",       "Cmss1",     "Nrp2",      "Dnajc9",    "Cks1b",     "Nudc",      "Yars",     
   "P3h2",      "Dgkz",      "Haus8",     "Get4",      "Ppp1r18",   "Naa50",     "Phgdh",     "RGD1563365",
   "RGD1565989","Tcof1",     "Tpi1",      "Pop1",      "Pak1ip1",   "Nup85",     "Sgpp1",     "Rgs10",    
   "Inpp1",     "Pih1d1",    "Smc2",      "Pycr3",     "Rbmx2",     "Hmgcs1",    "Tomm34",    "Rrp9",     
   "Rbbp8",     "Hpf1",      "Gemin6",    "Snrpa",     "Tuba1b",    "H2afx",     "Nrg1",      "Naa10",    
   "Bmp8b",     "Prpf4",     "Utp6",      "Pgk1",      "Ruvbl2",    "Dnajb3",    "Arpin",     "Fgd6",     
   "Taf1d",     "Timm8a1",   "Pja1",      "Ezh2",      "Rps6ka1",   "Mthfd1l",   "Ube2s",     "Nup155",   
   "Fasn",      "Umps",      "Odc1",      "Arl5a",     "Itga6",     "Ahcy",      "Nup54",     "Nxt1",     
   "Cd44",      "Jag1",      "Mcfd2",     "Fkbp4",     "Ddx18",     "Atp10d",    "Prkar2a",   "Snrpa1",   
   "Dynll2",    "Ppat",      "Dazap1",    "Hddc3",     "Ddx56",     "Diaph3",    "Atad3a",    "Cnot9",    
   "Pomgnt1",   "Col18a1",   "Ppih",      "Bud23",     "Stmn1",     "Dgkh",      "Mrps26",    "Lrrcc1",   
   "Lsm5",      "Nup107",    "Ninj1",     "Pa2g4",     "Hnrnpa1",   "Ppidl1",    "Aaas",      "Gpatch4",  
   "Ndufaf2",   "Rcl1",      "Rangap1",   "Uhmk1",     "Chchd6",    "Mrto4",     "Nolc1",     "Itgb4",    
   "Lsm3",      "Bri3bp",    "Degs1",     "Anp32e",    "Snu13",     "Rprd1a",    "Ppp5c",     "Trim27",   
   "Trmt6",     "Mrps5",     "Ints3",     "Htra1",     "Carnmt1",   "Nop56",     "Dohh",      "Sigmar1",  
   "Psip1",     "Nop58",     "Tma16",     "Cbx5",      "Uck2",      "Fst",       "Cd3eap",    "Dkc1",     
   "Rnf126",    "AC095947.1", "Ssrp1",     "Rbm28",     "Mrpl42",    "Tspan31",   "Mrps27",    "Nr2c2ap",  
   "Smyd2",     "AC127784.2", "Psph",      "Rrs1",      "Hspe1",     "Tmed5",     "Set",       "Lysmd2",   
   "Stip1",     "Dnajc2",    "Snrpf",     "Atp13a3",   "Mipol1",    "Pole4",     "Mrpl12",    "Sssca1", 
   "Cd83",      "Ranbp1",    "Id3",       "Tfdp1",     "Aatf",      "Lrrc59",    "Wdr43",     "Emg1",   
   "Cav2",      "Prmt5",     "Ruvbl1",    "Zfp593",    "Nucks1",    "Mak16",     "Hspd1",     "Gnl3",   
   "Slc7a1",    "Nradd",     "Rpa3",      "Smc6",      "Mbd3",      "Atic",      "Timm9",     "Rpf2",   
   "Gar1",      "Pitpnb",    "Got2",      "Otud6b",    "Ak6",       "Tubg1",     "Hikeshi",   "Prr7",   
   "Srsf7",     "Comt",      "Pkm",       "Tipinl1",   "Snrnp40",   "P4ha1",     "Ptges3l1",  "Ajuba",  
   "Selenoh",   "Dnajc15",   "Smn1",      "Gtf3a",     "Impdh1",    "Syncrip",   "Abce1",     "Ldlr",   
   "Sfpq",      "Enah",      "Gcsh",      "Nip7",      "Pus1",      "Pfdn4",     "Pbdc1",     "Iffo2",  
  "Rras2",     "Mphosph10", "Gtf2h1",    "Rrp15",     "Creld2",    "Mybbp1a",   "Polr3h",    "Nop14",    
 "Kdelr2",    "Ddx21",     "Nap1l1",    "Kpnb1",     "Eif1a",     "Akt1",      "Tmem120a",  "Fkbp3",    
 "Hprt1",     "Pabpc4",    "Nsun2",     "Slc25a4" 
  
)

Basal_Module_Score <- intersect(intersect(intersect(Starting.Basal_Features, P0.Basal_Features), P3.Basal_Features), Eng24Hr.Basal_Features)
Basal_Module_Score <- c(
   "Krt5",
   "Tp63",
   "Wnt10a",
   "Col17a1",
  "Itga6",
   "Comt",
   "Dst"
  
)

cat(Basal_Module_Score, sep = "\n")


P0.Hillock_Features <- c(
   "Krt13",     "Sfrp1",     "Pla2g4e",   "Serpinb3a", "Fads2l1",   "Krtdap",    "Tmprss11f", "Sprr1b",   
   "Fer1l4",    "Lipm",      "Adgrf4",    "Stfa3",     "S100a8",    "Slc5a1",    "Defb1",     "Il1a",     
   "Ces2g",     "Tmprss11g", "Krt16",     "Ly6d",      "Prdm1",     "Serpinb11", "Krt12",     "Dmkn",     
   "Dsg3",      "Rbp2",      "Tmprss11b", "Prss27",    "Cnfn",      "Gsdmc",     "Psapl1",    "Bcl2l15",  
   "Rdh12",     "Gcnt3",     "Lrrc26",    "Aldh1a3",   "Sprr1a",    "Abca12",    "Cers3",     "Mgll",     
   "Trex2",     "Tprg1",     "Prom2",     "Tmprss4",   "Sptssb",    "Tmem63c",   "Ankrd22",   "Serpinb2", 
   "Grhl3",     "Cwh43",     "Calml3",    "Ido2",      "Fut2",      "Gjb6",      "Gpr87",     "AC111804.2",
   "Trim29",    "Sult2b1",   "Ppm1j",     "Mall",      "Slc28a3",   "Rasgrp1",   "Scel",      "Rhcg",     
   "Ceacam1",   "Bcas1",     "Afap1l2",   "Clca2",     "Fxyd5",     "Tmem154",   "Aqp3",      "Crabp2",   
   "Mafb",      "Tnfrsf9",   "Gas7",      "Emp1",      "Tfap2c",    "Padi1",     "Nrarp",     "Gjb2",     
   "Arg1",      "Rab27b",    "Notch3",    "Klf4",      "Rhbg",      "Adh7",      "Cysrt1",    "Lypd6b",   
   "Runx2",     "Fam84a",    "Car13",     "Irf5",      "MGC105649", "Blnk",      "Adgrl3",    "Tmem246",  
   "Ptgr1",     "Tmem45b",   "Rhov",      "Krt1",      "Plekhn1",   "Pax9",      "B3galnt1",  "Znf750",   
   "Paqr5",     "Slurp1",    "Thbd",      "Gabrp",     "Bcl3",      "Catsperz",  "Tmcc3",     "Mdfi",     
   "Bnipl",     "Wdr72",     "Smox",      "Plekhg1",   "Serpina1",  "Hs3st1",    "Grhl1",     "P2ry2",    
   "Aldh3a1",   "Ovol1",     "Fam83b",    "Nectin4",   "Dusp5",     "Dgat2",     "Krt4",      "Frmd4b",   
   "Dsc2",      "Kank1",     "Dennd2c",   "Crybg2",    "Ehf",       "Il1rn",     "Zdhhc13",   "Tent5b",   
   "Plcd1",     "Cyp4f39",   "Pkp1",      "Ikzf2",     "Cryl1",     "Gdpd3",     "Pinlyp",    "Kctd1",    
   "Pcdh1",     "Etv1",      "Fxyd3",     "Eya2",      "Nectin1",   "Zc3h12a",   "Rab7b",     "Trim16",   
   "Hbegf",     "Farp2",     "Acp5",      "Itpkc",     "Capg",      "Sytl1",     "Fabp5",     "Ell2",     
   "Gltp",      "Icoslg",    "Kcnk7",     "Inava",     "Mapkapk3",  "Ldah",      "Lypd3",     "Epha1",    
   "Tmem54",    "Pld1",      "Slc6a20",   "Lynx1",     "Rnf19b",    "Perp",      "Pgm2",      "Hebp2",    
   "Hpse",      "Pygl",      "Sptbn2",    "Fam135a",   "Clock",     "Dsp",       "Macc1",     "Peak1",    
   "Fam160a1",  "Cldn4",     "Mpzl2",     "Tspan12",   "Atp8b1",    "Vps37b",    "Elf3",      "Anxa9",    
   "Atp13a4",   "Mxd1",      "Lad1",      "Anxa1",     "Dusp22",    "Nbeal2",    "Mink1",     "Mxd3",     
   "Mindy3",    "Dhrs1",     "Elovl1",    "Arf6",      "Zfp36l1",   "Ap3s1",     "Ier5",      "Evpl",     
   "Mgst3",     "S100a11",   "Abhd17c",   "Mid1ip1",   "Ptpn13",    "Junb",      "Tmbim1",    "Arhgap32", 
   "Arap2",     "Sri",       "Tacstd2",   "Relch",     "Ctsc",      "Bace2",     "S100a16",   "Adam17",   
   "Sh3bgrl3",  "Clint1",    "Prr13",     "Phlda1",    "Clip1",     "Pdzk1ip1",  "Rab3d",     "Rab25",    
   "Abracl",    "Rab11a",    "Cd9",       "Myo5b",     "Kdm5b",     "Ppl",       "Ripk4",     "Ucp2",     
   "Txn1",      "Vps53",     "Sdc1",      "Anxa7",     "Cast",      "Rab10",     "Jup",       "Bicdl2",   
   "Xpnpep1",   "Csnk1a1"
)

P3.Hillock_Features <- c(
   "Serpinb3a", "Adgrf4",    "Fads2l1",   "Slc5a1",    "Degs2",     "Sprr3",     "Cwh43",     "Prdm1",    
   "Tmprss11b", "Sprr1b",    "Prss27",    "Fer1l4",    "Trex2",     "Stfa3",     "Psapl1",    "Gjb6",     
   "Tmprss11g", "Tprg1",     "Ly6d",      "Tmem154",   "Dmkn",      "Tmprss4",   "Nrg4",      "Bcl2l15",  
   "Calml3",    "Acsbg1",    "Tmprss11f", "Kap",       "Defb1",     "Ada",       "Slurp1",    "Serpinb11",
   "Cnfn",      "Atp6v0a4",  "Gsdmc",     "Cd68",      "Sprr1a",    "Krt16",     "Gjb2",      "Hs3st6",   
   "Chl1",      "Rhbg",      "Krt1",      "Sult2b1",   "Them5",     "Krt12",     "Clca2",     "Prom2",    
   "Krt13",     "Arg1",      "Bnipl",     "Cysrt1",    "Grhl3",     "Tmem45b",   "Mall",      "Gpr87",    
   "Aqp3",      "Nectin4",   "Mboat2",    "Gpr160",    "Gas7",      "Irf5",      "Dsg3",      "Cyp4f39",  
   "Adtrp",     "MGC105649", "Rbp2",      "Acap1",     "Paqr5",     "Abhd14a",   "Rab27b",    "Padi1",    
   "Fam84a",    "Mycl",      "Plekhn1",   "Adh7",      "Crabp2",    "Dennd2c",   "Klf4",      "Thrb",     
   "Sipa1l2",   "Scel",      "Tmem246",   "Pdzd2",     "Serpinb2",  "Gchfr",     "Mxd1",      "Znf750",   
   "Nectin1",   "Grhl1",     "Lpar1",     "Ndrg1",     "Catsperz",  "Emp1",      "Rhov",      "Acp5",     
   "Ovol1",     "B3galnt1",  "Zdhhc13",   "Mafb",      "Gltp",      "Cpne8",     "Cst6",      "Lynx1",    
   "Sept5",     "Frmd4b",    "Nrarp",     "Gstm1",     "Eya2",      "Fabp5",     "Ankrd22",   "Trim29",   
   "Cryl1",     "Xkr4",      "Dgat2",     "Hpse",      "Myo5b",     "Pax9",      "Pdzk1ip1",  "Rhbdl2",   
   "Ero1a",     "Atp13a4",   "Serpinb1a", "Cers3",     "Pcdh1",     "Plcd1",     "Ptgr1",     "Pygl",     
   "Dsp",       "Pkp1",      "Fam110c",   "Fxyd3",     "Lypd3",     "Epha1",     "Perp",      "Evpl",     
   "Ehf",       "Abcc4",     "Pinlyp",    "Pitx1",     "Cd24",      "Bmp2",      "Hsbp1l1",   "Dusp5",    
   "P2ry2",     "Etv1",      "Dsc2",      "Kctd1",     "Kcnk7",     "Bambi",     "Mapkapk3",  "Cds1",     
   "Higd1a",    "Tmem50b",   "Ell2",      "Atp11b",    "Hebp2",     "Dusp22",    "Tent5b",    "Mxd3",     
   "Myo6",      "Fam162a",   "Trim16",    "Crybg2",    "Nampt",     "Hmox1",     "Rab3d",     "Adam17",   
   "Pcyt1a",    "Anxa1",     "Ikzf2",     "Junb",      "Jup",       "Tacstd2",   "Tmbim1",    "Zbtb7a",   
   "Ivns1abp",  "Txn1",      "Sc5d",      "Tfap2a",    "Zfp36l1",   "Sdc1",      "Hebp1",     "Macc1",    
   "Cast",      "Sh3bgrl3",  "Clock",     "Arap2",     "Phlda1",    "Ethe1",     "RGD1305347","Slk",      
   "Clint1",    "Mycbp2",    "Prr13",     "Rab11fip1", "Mindy1",    "Mettl7a",   "Reep3",     "Hsdl2",    
   "Stap2",     "S100a16",   "Twf1",      "Ppl",       "Arf6",      "Klc3",      "Mpzl2",     "Pyurf",    
   "Ctsd",      "Abhd17c",   "Cd9",       "Mgst3",     "Lad1",      "Tmem254",   "Smim29",    "Ldhb",     
   "Hspb1",     "Trim8",     "Ggct",      "Clip1",     "Nudt9",     "Kdm5b",     "Afdn",      "Chp1",     
   "Rab11a",    "Arhgap17",  "Itm2b",     "Urod",      "Ap3s1",     "Dnajb1",    "Foxn3",     "Nucb2",    
   "Eps8l2",    "Cdkn2b",    "Ucp2",      "Tmem205",   "S100a11",   "Id1",       "Rab10",     "Rab25",    
   "Hopx",      "Klf5",      "Taldo1",    "Tmem123",   "Cd47",      "Btbd1",     "Tmem134",   "Rit1",     
   "Anxa7",     "Csnk1a1",   "Erp44",     "Sqor",      "Polr1d",    "Cd59",      "Fam129b",   "Map1lc3a", 
   "Oxr1",      "Snrnp25",   "Tpd52",     "Mob4",      "Clta",      "Mkrn1",     "Cmpk1",     "Arpc1a",   
   "Lgals3",    "Vegfa",     "Prnp",      "Atp6ap1",   "Dynlt3",    "Etfb",      "Ripk4",     "Prdx5",    
   "Tmem9b",    "Marcks",    "Pdlim2",    "Ptprf",     "Leprotl1",  "Bnip3l",    "Avpi1" 
)


Eng24Hr.Hillock_Features <- c(
   "Adgrf4",      "Dsg1",        "Acer1",       "Prss27",      "Sprr3",       "Nccrp1",      "Stfa3",      
   "Fads2l1",     "Gpha2",       "Lipm",        "Cwh43",       "Crct1",       "Tprg1",       "Elovl4",     
   "Sdr9c7",      "Tmprss11b",   "Trex2",       "Aspg",        "Degs2",       "Gcnt3",       "Fer1l4",     
   "Tmem45b",     "Tmprss4",     "Il22ra1",     "Sprr1b",      "Abca12",      "Cd68",        "Krt78",      
   "Crisp3",      "Calml3",      "Gdpd3",       "Krt13",       "Fxyd4",       "Psapl1",      "Rap1gap",    
   "Psca",        "Serpinb3a",   "Tmprss11f",   "Tmprss11g",   "Bnipl",       "Fa2h",        "Pla2g4e",    
   "Sult2b1",     "Sprr1a",      "Cnfn",        "Prdm1",       "Slco2a1",     "Csta",        "Slurp1",     
   "Lypd8",       "Ly6d",        "Dmkn",        "Slc5a1",      "Elf5",        "Cysrt1",      "Krt1",       
   "Sbsn",        "Ada",         "Hsbp1l1",     "Nrg4",        "S100a8",      "Fam3b",       "Gchfr",      
   "Prom2",       "Ceacam1",     "Lrrc26",      "Plat",        "Serpinb11",   "Anxa9",       "Yod1",       
   "Pdzd2",       "Tmem154",     "Fut2",        "Krt16",       "Mxd1",        "Krt23",       "Paqr5",      
   "Bcl2l15",     "Grhl3",       "Bcas1",       "Gpr160",      "Atp13a4",     "RGD1305207",  "Nectin4",    
   "Aldh1a3",     "Cyp4f39",     "Sept5",       "Gas7",        "Arg1",        "Gpr87",       "Mal",        
   "Sdcbp2",      "Ecm1",        "Grhl1",       "Pdzk1ip1",    "Rnf39",       "Tmie",        "MGC105649",  
   "Upk1b",       "Syt8",        "Scel",        "Rhbg",        "Sipa1l2",     "Acbd4",       "Rasip1",     
   "Zfp185",      "Ankrd22",     "Rdh10",       "Dgat2",       "Lynx1",       "Tyro3",       "Abhd14a",    
   "Spns2",       "Tmem246",     "Scnn1a",      "Maff",        "Evpl",        "Ndrg1",       "Cldn1",      
   "Ctla2a",      "Epn3",        "Gltp",        "Ovol1",       "Clic3",       "Ido2",        "Wdr72",      
   "Rab15",       "Rnf208",      "RGD1562378.1","Pcdh1",       "Tmem50b",     "Emp1",        "Plcd3",      
   "Glrx",        "Plekhn1",     "P2ry2",       "Hopx",        "Cpeb2",       "Padi1",       "Tent5b",     
   "Grb7",        "Krt12",       "Hexb",        "Plcd1",       "Cst6",        "Epha1",       "Bace2",      
   "Bcl3",        "Ctsd",        "Rab27b",      "Fam84a",      "RGD1561662",  "Zswim4",      "Abhd17b",    
   "Tp53inp2",    "Hspb1",       "Cldn23",      "Dsg3",        "Rbp2",        "Fbxo32",      "Aqp3",       
   "Dusp5",       "Bicdl2",      "Ankrd9",      "Myo6",        "Il1rn",       "Ppl",         "Smox",       
   "Krt80",       "Mafb",        "Mxd3",        "Exph5",       "Rhbdl2",      "Eps8l1",      "Abhd5",      
   "Pllp",        "Pinlyp",      "Lgalsl",      "Nhsl1",       "Perp",        "March3",      "Cds1",       
   "Ypel3",       "Klf4",        "Pof1b",       "Nucb2",       "Dsp",         "Fos",         "Sptbn2",     
   "Klc3",        "Hebp2",       "Cyp3a9",      "Lypd3",       "Il1a",        "Cd24",        "RGD1562378.2",
   "Eps8l2",      "Mindy1",      "Cpeb4",       "Elf3",        "Rab11fip1",   "Atp8b1",      "Cdkn1b",     
   "Nrarp",       "Slc20a1",     "Abhd17c",     "Alas1",       "Crybg2",      "Ubl7",        "Rab3d",      
   "Rhov",        "Vps37b",      "Fxyd3",       "RGD1305347",  "Gnal",        "Pgm2",        "Rufy1",      
   "Erbb3",       "Dusp22",      "Tmbim1",      "Elovl1",      "Anxa1",       "Ethe1",       "Uaca",       
   "Zdhhc13",     "Chp1",        "Isg20",       "Junb",        "Myo5b",       "Dusp14",      "Zfyve19",    
   "Qsox1",       "Syngr1",      "Pitx1",       "Ttc9",        "Tmod3",       "Errfi1",      "Tacstd2",    
   "Sept8",       "Rab11a",      "Sat1",        "Zfand5",      "Ier5",        "Timp2",       "Map1lc3a",   
   "Jup",         "AC134224.3",  "Ldhb",        "Mid1ip1",     "Ell2",        "Zfp36",       "Cd59",       
   "Tbc1d14",     "Gabarapl2",   "Wasl",        "Adgrl2",      "Tspan8",      "Cast",        "Hs3st1",     
   "Mkrn1",       "Prnp",        "Capg",        "Hist1h2bcl1", "Zfp36l1",     "Mpzl3",       "Itsn2",      
   "Fam107b",     "Afdn",        "Arf6",        "Ndel1",       "Ypel5",       "Pacsin3",     "Cgnl1",      
   "Tgm1",        "Mapk6",       "Sh3d19",      "Wwtr1",       "Trim16",      "Mpzl2",       "Fam129b",    
   "Avpi1",       "Metrnl",      "Ppp1r14c",    "Txn1",        "Atp6ap2",     "Ide",         "Bnip3l",     
   "Mapk3",       "Psenen",      "Taldo1",      "Ppp2r2a",     "Pdlim2",      "Ubc",         "Ier2",       
   "Pnpla8",      "Aktip",       "Nudt9",       "Lmo7",        "Reep3",       "Atp6v1g1",    "Dsc2",       
   "Ctsa",        "Macc1",       "Osbpl3",      "Usp6nl",      "Gabarap",     "Atp6v1e1",    "Clip1",      
   "Pnrc1",       "S100a16",     "Cd9",         "Mien1",       "Lrrfip1",     "Acadl",       "Myzap",      
   "Btg1",        "Chmp2b",      "Phlda1",      "Klf3",        "Arl8b",       "Rab10",       "Dhrs1",      
   "Uqcr10",      "Atf4",        "Wdfy1",       "Map1lc3b",    "Clint1",      "Atp5if1",     "Prdx5",      
   "Dusp1",       "Klf5",        "Lgals3",      "Gprc5a",      "S100a11",     "Prr13",       "Spint1",     
   "Vat1",        "Urod",        "Lad1",        "Vps4b",       "Ikzf2",       "Cldn4",       "Pkp1",       
   "Acsl3",       "Mal2",        "Chmp2a",      "Ap3s1",       "Me1",         "Sar1b",       "Rab25",      
   "Scamp2",      "Chmp5",       "Ssu72",       "Arpc1a",      "Tax1bp1",     "Sin3b",       "Kdm5b",      
   "Sec62",       "Cdkn2b",      "Ndfip2",      "Spryd7",      "Brk1",        "Eif1",        "Chic2",      
   "Etfb",        "Rab7a",       "Ifrd1",       "Sri",         "Sh3glb1",     "Aldoa",       "Cltb",       
   "Cib1",        "Atp6v0b",     "Abi1",        "Tmem134",     "Rala",        "Gpx2",        "Hadhb",      
   "Pdcd10",      "Rab14",       "Ubl5",        "Anxa7",       "Mea1",        "Sem1",        "Cox7a2",     
   "Mob4",        "Ppp1cb",      "Fis1",        "Arpc5l",      "Dstn",        "Atp6v0e1"  
)



FiveDay.Hillock_Features <- c(
   "Cxcl17",      "Clec2e",      "Clca4l",      "Slc39a4",     "Serpina1",    "Muc20",       "Ceacam1",    
   "Prdm1",       "Scel",        "S100a8",      "Wnt11",       "Cd68",        "Cndp1",       "Rac2",       
   "S100a9",      "Pllp",        "Bace2",       "Tcp11l2",     "Krt13",       "Cx3cl1",      "Plau",       
   "Mal",         "Plat",        "Aif1l",       "Calcb",       "Entpd3",      "Il1a",        "Mxd1",       
   "Maff",        "Fcmr",        "Ctla2a",      "Hopx",        "Blnk",        "Apobec1",     "Pinlyp",     
   "Pigr",        "Thrb",        "Fxyd5",       "Il1rn",       "Rhpn1",       "Gchfr",       "Mfsd4a",     
   "Ggt1",        "Irf1",        "Isg20",       "Slc44a4",     "Cebpd",       "Hsd11b1",     "Upk3bl1",    
   "Dusp5",       "C3",          "Hist1h2bcl1", "Pdzk1ip1",    "Fam110c",     "Rab11fip1",   "Cysrt1",     
   "Ramp2",       "Cyp3a9",      "Muc1",        "Duox2",       "Smpdl3a",     "Wfdc2",       "Cxcl3",      
   "Plet1",       "Ms4a8",       "Grhl3",       "Gdf15",       "Cldn3",       "Ifi27l2b",    "MGC105649",  
   "Insig1",      "Hs3st1",      "Cldn7",       "Bcl3",        "Cd55",        "Tmie",        "Aldoc",      
   "Mal2",        "Tgm2",        "Tspan1",      "Rhov",        "Ypel3",       "Cldn23",      "Nr1d1",      
   "Mgat4a",      "Csnk1e",      "RGD1561662",  "Slco2a1",     "Prr15",       "Spty2d1",     "RT1-M3-1",   
   "Paqr5",       "Spns2",       "Vps28",       "Aldh3a1",     "Gadd45b",     "Ddit3",       "Prune1",     
   "Serpinb1a",   "Alas1",       "Cndp2",       "Tapbp",       "Dedd2",       "Krt18",       "Lpcat4",     
   "Dnajb9",      "Junb",        "Tecpr1",      "Ctsd",        "Srd5a1",      "Hpse",        "Erbb3",      
   "Tbcc",        "Cd24",        "Smox",        "Tprn",        "Rhpn2",       "Arhgef16",    "Elf3",       
   "Atf3",        "Kcnk7",       "S100a4",      "Acap1",       "Cblc",        "Vps37b",      "Emp1",       
   "Tacstd2",     "Glrx",        "Hexb",        "St3gal1",     "Krt19",       "Gabarapl1",   "Spint1",     
   "Osgin1",      "Nampt",       "Cldn4",       "Arl1",        "Casp7",       "Rala",        "Jund",       
   "Dusp10",      "Pard6b",      "Cd59",        "Mien1",       "Tmem184b",    "Irak2",       "Arf6",       
   "Rfk",         "S100a16",     "Tmsb4x",      "Prss22",      "Sc5d",        "Efna1",       "Rhoc",       
   "Cited2",      "Dcaf12",      "Fth1",        "Srpra",       "Syngr1",      "Serpinb2",    "B2m",        
   "Timp2",       "Akr1b8",      "Rassf7",      "Mindy1",      "Med24",       "Tspan8",      "Gprc5a",     
   "Txnip",       "Zfand5",      "Sat1",        "Metrnl",      "Fabp5",       "Tor1aip2",    "Ghitm",      
   "Gch1",        "Tmem189",     "Zfp36",       "Dusp1",       "Taldo1",      "Isca1",       "Tmbim4",     
   "Efhd2",       "Tnfrsf21",    "Aldoa",       "Cript",       "Bicdl2",      "Anxa1",       "Errfi1",     
   "Golga7",      "RGD1562378.2","Ppp1r15a",    "Klf4",        "Eif4ebp1",    "Tprg1l",      "Ocln",       
   "Anxa2",       "Sf3b6",       "Klf5",        "Ier5",        "RGD1561149",  "Nectin2",     "Ankrd37",    
   "Rnaset2",     "Gabarapl2",   "Adrm1",       "Krt8",        "Cir1",        "Ctsb",        "Itm2b",      
   "Sh3yl1",      "Hmox1",       "Map1lc3b",    "Slc50a1",     "Gadd45g",     "Cxcl16",      "Wnt4",       
   "Mea1",        "Ctsa",        "Cdkn1a",      "Bspry",       "Pof1b",       "Hspb1",       "Pdlim1",     
   "Cmas",        "Pla2g12a",    "Proser2",     "Myl12b",      "Cd164",       "Adm",         "Tmem171",    
   "Arf4",        "Ubc",         "Cd9",         "Grb7",        "Ier2",        "Ubb",         "Tob1",       
   "Gabarap",     "RT1-CE10",    "Mkrn1",       "Mt-nd5",      "Trim27",      "Ypel5",       "Sqstm1",     
   "Ing2",        "Ddx47",       "Nudt4",       "Emb",         "Eif4h",       "Eps8l2",      "Gnal",       
   "Tgif1",       "Selenok",     "Bri3",        "Nus1",        "Mapk3",       "Gmfb",        "RT1-CE4",    
   "Klf3",        "Avpi1",       "Naxd",        "Atf4",        "Krtcap3",     "Grn",         "Tusc2",      
   "Irx1",        "Btg1",        "Insig2",      "Best1",       "Spsb1",       "Ero1a",       "Rab11a",     
   "Mpv17l2",     "Ubl3",        "Pnrc1",       "Tm2d2",       "Ufm1",        "Il33",        "Fxyd3",      
   "Chmp5",       "Smim22",      "Supt4h1",     "F11r",        "Degs1",       "Rer1",        "Ssu72",      
   "Selenos",     "Mrpl52",      "Psenen",      "Alkbh5",      "Pmm1",        "Cd47",        "Vdac2",      
   "Atp6v0c",     "Napa",        "Pmaip1",      "Tbrg1",       "Syf2",        "Gapdh",       "Sft2d1",     
   "Zfp36l2",     "Fuca1",       "Sod2",        "Bet1",        "RT1-CE1",     "Yipf4",       "Lgals3",     
   "Med28",       "S100a6",      "Imp3",        "Pdcd6",       "Eif1",        "Bola2",       "Oser1",      
   "Ddt",         "Sar1b",       "Pgk1",        "Mrps18b",     "Actr1b",      "Nsa2",        "Mapkapk2",   
   "Dad1",        "Serp1",       "Cox6b1.1",    "Gltp",        "Golph3",      "Atp6v0b",     "Ifrd1",      
   "Aamp",        "Sh3bgrl3",    "Tmem248",     "Nat9",        "Snx18",       "Mrps35",      "Rps27",      
   "RGD1562402",  "AC095947.3",  "Bloc1s2",     "Cox5b",       "Capn1",       "Psme2",       "Rnpep",      
   "RT1-A2",      "Zbed5",       "R3hdm4",      "Eif3f",       "Cox8a",       "Paip2",       "Pmvk",       
   "Tmem59",      "Gm2a",        "Pdcd2",       "Tmem183a",    "Slc25a39",    "Cox4i1",      "Ptges",      
   "Kdelr2",      "Tmem134",     "Cyp51",       "Rpl18",       "Cacfd1",      "Sri",         "Lamtor4",    
   "Chic2",       "Atp1b1",      "Atp6v0e1",    "Cox6b1",      "Sec22b",      "Dars",        "Rpl27a",     
   "Uqcr10",      "Rac1",        "Brk1",        "Nit1",        "Cyb5a",       "Rabac1",      "Bcl10",      
   "Msmo1",       "Hist1h1e",    "Emc7",        "Sec61g",      "Znrd1",       "Ppp6c",       "Serf2",      
   "Eif3g",       "Polr1d",      "Anxa7",       "Krtcap2",     "Sh3glb1",     "Ckap4",       "Derl1",      
   "Adipor1",     "Tm2d1",       "Pttg1ip",     "Rpp40",       "Rps29",       "Vapa",        "Rps28",      
   "Rpl41",       "Coro1b",      "S100a11",     "Gon7",        "Kdelr1",      "Rpl32.1",     "Mrpl15",     
   "Pfdn5",       "Golt1b",      "Pgam1",       "Gpi",         "Map1lc3a",    "Rtn3",        "Nfkbia",     
   "Ost4",        "Saraf",       "Crybb1",      "Ppp1cb",      "Uqcrh",       "Edf1",        "Tmed2",      
   "Dynlrb1",     "Tmem179b",    "Psmd8",       "Krt7",        "Rps10",       "Plp2",        "Ube2d3",     
   "Prr13",       "Cers2",       "Acbd3",       "Uba52",       "Eef1a1",      "Rpl32",       "Rps19",      
   "Arpc3",       "Med10",       "Rpl37",       "Pcnp",        "Gpx4",        "Aimp1",       "Lamtor5",    
   "Pet100",      "Cox7c",       "Lamtor1",     "Lasp1",       "Mrpl32",      "Brms1",       "Clta",       
   "Csnk2b",      "Eif3m",       "Atp5f1e",     "Ndfip1",      "Rab5c",       "Cdv3",        "Psmb4",      
   "Fam104a",     "Sdcbp",       "Sars",        "Psme1",       "Rpl10",       "Carhsp1",     "AC141489.1", 
   "Iah1",        "Pold4",       "Arpc4",       "Arpc5l",      "Rpl24",       "Chmp2a",      "Sys1",       
   "Snx3",        "Mcts1",       "Atp5mc2",     "Rps21",       "Rpl17",       "Bsg",         "Rpl39",      
   "Rpl30",       "Rpl21.1",     "AC105662.1",  "Ybx3",        "Ptp4a2",      "Trappc2l",    "Rpl14",      
   "Grpel1",      "Rps10l1",     "Ifi27",       "Rps13",       "Chmp2b",      "Rps23",       "Rpl7",       
   "Rpl37a",      "Rpl21.3",     "Rps5",        "Rpl13",       "Rpl36",       "Rpl35",       "Rpl26",      
   "Rpl28",       "Rps18",       "Rpl19"
  
)

Hillock_Module_Score <- intersect(intersect(intersect(P0.Hillock_Features, P3.Hillock_Features), Eng24Hr.Hillock_Features), FiveDay.Hillock_Features)

Hillock_Module_Score <- c(
"Krt13",     "Prdm1",     "Grhl3",     "Scel",      "Emp1",      "Klf4",      "Cysrt1",    "MGC105649", "Rhov",     
 "Paqr5",     "Dusp5",     "Pinlyp",    "Fxyd3",     "Gltp",      "Mxd1",      "Anxa1",     "Arf6",      "S100a11",  
"Junb",      "Tacstd2",   "S100a16",   "Prr13",     "Pdzk1ip1",  "Rab11a",    "Cd9",       "Anxa7"    
)
